package ch.bbw.jg.ConsoleCalculatorWithMaven;

/**
 * 
 * @author Joel Galli
 * @version 19.01.2020
 *
 */

public class App {
	public static void main(String[] args) {
		Calculator calculator = new Calculator();
		int valueA = 0;
		int valueB = 0;
		int valueANeg = 0;
		int valueBNeg = 0;
		int valueZero = 0;
		int valueMax = 0;
		int valueMin = 0;

		System.out.println("========================================================================");
		System.out.println("Console Calculator");
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("");

		valueA = 10;
		valueB = 20;
		valueANeg = -10;
		valueBNeg = -20;
		valueZero = 0;
		valueMax = Integer.MAX_VALUE;
		valueMin = Integer.MIN_VALUE;

		System.out.println("========================================================================");
		System.out.println("Addition");
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSumOfTwoPositiveIsOk()");
		System.out.println("========================================================================");
		System.out.println("Sum " + valueA + " + " + valueB + " = " + calculator.sum(valueA, valueB));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("");
		System.out.println("========================================================================");
		System.out.println("Subtraction");
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSubtrOfTwoPositiveIsOk()");
		System.out.println("========================================================================");
		System.out.println("Difference " + valueA + " - " + valueB + " = " + calculator.subtr(valueA, valueB));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("");
		System.out.println("========================================================================");
		System.out.println("Division");
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testDivOfPositiveByPositiveUnexpectArithmethicException()");
		System.out.println("========================================================================");
		System.out.println("Quotient " + valueA + " / " + valueB + " = " + calculator.div(valueA, valueB));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("");
		System.out.println("========================================================================");
		System.out.println("SquareRoot");
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testProtectedSqrtMethodWithPositive()");
		System.out.println("========================================================================");
		System.out.println("SquareRoot " + Math.sqrt(valueA) + " = " + calculator.sqrt(valueA));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("");
		System.out.println("========================================================================");
		System.out.println("Multiplication");
		System.out.println("========================================================================");		
		System.out.println("");
		System.out.println("Current Test: testPackageProtectedMultMethodWithPositive()");
		System.out.println("========================================================================");
		System.out.println("Product " + valueA + " * " + valueB + " = " + calculator.div(valueA, valueB));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("");
		System.out.println("========================================================================");		
		System.out.println("Power");
		System.out.println("========================================================================");		
		System.out.println("");
		System.out.println("Current Test: testPrivatedPowMethodWithPositive()");
		System.out.println("========================================================================");		 
		// System.out.println("Product " + 3 + " ^ " + 2 + " = " + calculator.pow(valueA, valueB));
		// Cannot test private Method
		System.out.println("Cannot test private method");
		System.out.println("========================================================================");
		System.out.println("");
		
		/*
		System.out.println("==================");
		System.out.println("Addition");
		System.out.println("==================");
		System.out.println("");
		System.out.println("Current Test: testSumOfTwoPositiveIsOk()");
		System.out.println("========================================================================");
		System.out.println("Sum " + valueA + " + " + valueB + " = " + calculator.sum(valueA, valueB));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSumOfTwoNegativeIsOk()");
		System.out.println("========================================================================");
		System.out.println("Sum " + valueANeg + " + " + valueBNeg + " = " + calculator.sum(valueANeg, valueBNeg));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSumOfOneNegativeOnePositiveIsOk()");
		System.out.println("========================================================================");
		System.out.println("Sum " + valueANeg + " + " + valueB + " = " + calculator.sum(valueANeg, valueB));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSumOfOnePositiveOneNegativeIsOk()");
		System.out.println("========================================================================");
		System.out.println("Sum " + valueA + " + " + valueANeg + " = " + calculator.sum(valueA, valueANeg));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSumOfZeroAndNegativeIsOk()");
		System.out.println("========================================================================");
		System.out.println("Sum " + valueZero + " + " + valueANeg + " = " + calculator.sum(valueZero, valueANeg));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSumOfZeroAndPositiveIsOk()");
		System.out.println("========================================================================");
		System.out.println("Sum " + valueZero + " + " + valueA + " = " + calculator.sum(valueZero, valueA));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSumMaxAndMaxGivesException()");
		System.out.println("========================================================================");
		System.out.println("Sum " + valueMax + " + " + valueMax + " = " + calculator.sum(valueMax, valueMax));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSumMaxAndMinIsOk()");
		System.out.println("========================================================================");
		System.out.println("Sum " + valueMax + " + " + valueMin + " = " + calculator.sum(valueMax, valueMin));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("");
		System.out.println("==================");
		System.out.println("Subtraction");
		System.out.println("==================");
		System.out.println("");
		System.out.println("Current Test: testSubtrOfTwoPositiveIsOk()");
		System.out.println("========================================================================");
		System.out.println("Difference " + valueA + " - " + valueB + " = " + calculator.subtr(valueA, valueB));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSubtrOfTwoNegativeIsOk()");
		System.out.println("========================================================================");
		System.out.println("Difference " + valueANeg + " - " + valueBNeg + " = " + calculator.subtr(valueANeg, valueBNeg));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSubtrOfOnePositiveAndOneNegativeIsOk()");
		System.out.println("========================================================================");
		System.out.println("Difference " + valueA + " - " + valueANeg + " = " + calculator.subtr(valueA, valueANeg));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSubtrOfOneNegativeAndOnePositiveIsOk()");
		System.out.println("========================================================================");
		System.out.println("Difference " + valueANeg + " - " + valueA + " = " + calculator.subtr(valueANeg, valueA));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSubrtMaxOfMaxGivesException()");
		System.out.println("========================================================================");
		System.out.println("Difference " + valueMax + " - " + valueMax + " = " + calculator.subtr(valueMax, valueMax));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSubtrZeroOfZeroIsOk()");
		System.out.println("========================================================================");
		System.out.println("Difference " + valueZero + " - " + valueZero + " = " + calculator.subtr(valueZero, valueZero));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSubtrZeroOfNegativeIsOk()");
		System.out.println("========================================================================");
		System.out.println("Difference " + valueA + " - " + valueZero + " = " + calculator.subtr(valueA, valueZero));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testSubrtMaxOfMMinIsOk()");
		System.out.println("========================================================================");
		System.out.println("Difference " + valueMin + " - " + valueMax + " = " + calculator.subtr(valueMin, valueMax));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("");
		System.out.println("==================");
		System.out.println("Division");
		System.out.println("==================");
		System.out.println("");
		System.out.println("Current Test: testDivOfPositiveByZeroThrowsExpectedArithmethicException()");
		System.out.println("========================================================================");
		System.out.println("Quotient " + valueA + " / " + valueZero + " = " + calculator.div(valueA, valueZero));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testDivOfNegativeByZeroThrowsExpectedArithmethicException()");
		System.out.println("========================================================================");
		System.out.println("Quotient " + valueANeg + " / " + valueZero + " = " + calculator.div(valueANeg, valueZero));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testDivOfZeroByZeroThrowsExpectedArithmethicException()");
		System.out.println("========================================================================");
		System.out.println("Quotient " + valueZero + " / " + valueZero + " = " + calculator.div(valueZero, valueZero));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testDivOfPositiveByPositiveUnexpectArithmethicException()");
		System.out.println("========================================================================");
		System.out.println("Quotient " + valueA + " / " + valueB + " = " + calculator.div(valueA, valueB));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testDivNegativeByNegativeisOk()");
		System.out.println("========================================================================");
		System.out.println("Quotient " + valueANeg + " / " + valueBNeg + " = " + calculator.div(valueANeg, valueBNeg));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testDivMAXAndPositiveIsOk()");
		System.out.println("========================================================================");
		System.out.println("Quotient " + valueMax + " / " + 1 + " = " + calculator.div(valueMax, 1));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testDivMAXAndNegativeIsOk()");
		System.out.println("========================================================================");
		System.out.println("Quotient " + valueMax + " / " + valueANeg + " = " + calculator.div(valueMax, valueANeg));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("Current Test: testDivPositiveAndNegativeIsOk()");
		System.out.println("========================================================================");
		System.out.println("Quotient " + valueA + " / " + valueANeg + " = " + calculator.div(valueA, valueANeg));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("");
		System.out.println("==================");
		System.out.println("SquareRoot");
		System.out.println("==================");
		System.out.println("");
		System.out.println("Current Test: testProtectedSqrtMethodWithPositive()");
		System.out.println("========================================================================");
		System.out.println("SquareRoot " + Math.sqrt(valueA) + " = " + calculator.sqrt(valueA));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("");
		System.out.println("==================");
		System.out.println("Multiplication");
		System.out.println("==================");
		System.out.println("");
		System.out.println("Current Test: testPackageProtectedMultMethodWithPositive()");
		System.out.println("========================================================================");
		System.out.println("Product " + valueA + " * " + valueB + " = " + calculator.div(valueA, valueB));
		System.out.println("========================================================================");
		System.out.println("");
		System.out.println("");
		System.out.println("==================");
		System.out.println("Power");
		System.out.println("==================");
		System.out.println("");
		System.out.println("Current Test: testPrivatedPowMethodWithPositive()");
		System.out.println("========================================================================");
		 // System.out.println("Product " + 3 + " ^ " + 2 + " = " + calculator.pow(valueA, valueB));
		 // Cannot test private Method
		System.out.println("Cannot test private method");
		System.out.println("========================================================================");
		System.out.println("");
		*/
	}
}
