language: java
sudo: false
script: mvn install
before_deploy:
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: ctC4lGk1PJqDbEh9UNNo38CdpaLhnwxn75+LaY+a3FRWrRlazYjQZlEAHmjQCxr3zsNxbf/6jqOBH8eOVyGsgAtIRW2a3FACErqef5BXPq+k+0xJ7bcYUDmjGQ9f8teQ5ATnPhMTW8O1Ssw+Jd9ffY207irj0bl9v3o6uoVG6Q4sTfbIYXkaDB+pkZWzpRGUpmHZw3Lw6dQmskpxcimODeGBTnhPz2pmdY/jSFIgi8JeCmWdmsTAcYZACmEE/9JqgPEzseqsGW1QRk4qvIzSFQtzbzXWLcXeeg3jDnLmI+oG5uBvdZ7k///tQ9vcT5LKIRV1jRwJbkctnAzNzC6HKwb1DDjbiRSeK5Yyw2aZzCwobkH3MxHSXpFtaQ7JMy0nA8AfY4McrQhJBu/fhSIa1XiOt6tO0zwzSs/nQAn65NA0xdYYyF/ff6ANxi08GkQX4sv+xTqvPvXugJhQoOF/TcKzdlQ8Qvi9sgqMtiVymzgPIUDUoBeWkvPBUScKBq8LWBIq1PPnh9P7qY5UY2tLYM5FzROXXzj8yN2Ko35ilHbUV1b3ypTJKLM8FLPT5040n/pvB4/iOxnkumNe79SwB4UNdLY0vq7jDXUPriZIaXy/8PZljUmhv+rrhAu5hjAADtHyCob43ilsBdW8OaBigxfxJ43RW8aTu010TMD5Lx0=
  file: "/home/travis/.m2/repository/ch/bbw/ConsoleCalculatorWithMaven/0.0.1-SNAPSHOT/ConsoleCalculatorWithMaven-0.0.1-SNAPSHOT.jar"
  on:
    repo: NoConsx/ConsoleCalculatorWithMaven
